# Simple math ops with Numpy - Scalars, vectors, matrices, tensors

In [1]:
import numpy as np

### Scalars

In [13]:
s = np.array(5)
print(s)
print(s.shape)
print(s + 3)

5
()
8


### Vectors

In [14]:
v = np.array([1,2,3])
print(v)
print(v[1])
print(v[1:])

[1 2 3]
2
[2 3]


### Matrices

In [15]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m)
print(m.shape)
print(m[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
6


### Tensors

In [21]:
t = np.array([[[[1],[2]], [[3],[4]], [[5],[6]]],
              [[[7],[8]], [[9],[10]], [[11],[12]]], 
              [[[13],[14]], [[15],[16]], [[17],[17]]]])
print(t)
print(t.shape)
print(t[2][1][1][0])

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]
(3, 3, 2, 1)
16


### Reshaping

In [30]:
v = np.array([1,2,3,4])
print(v)
print(v.shape)
print(v.reshape(1,4))
print(v.reshape(4,1))

[1 2 3 4]

(4,)

[[1 2 3 4]]

[[1]
 [2]
 [3]
 [4]]


### Elementwise operations - Addition

In [27]:
values = [1,2,3,4,5]
print(values)
values = np.array(values) + 5
print(values)

[1, 2, 3, 4, 5]
[ 6  7  8  9 10]


### Elementwise operations - Multiplication

In [28]:
values = [1,2,3,4,5]
values = np.array(values)
x = np.multiply(values, 5)
print(x)
x = values * 5
print(x)

[ 5 10 15 20 25]
[ 5 10 15 20 25]


### Elementwise matrix operations - Addition

In [29]:
a = np.array([[1,3], [5,7]])
b = np.array([[2,4], [6,8]])
print(a)
print(b)
print(a + b)

[[1 3]
 [5 7]]

[[2 4]
 [6 8]]

[[ 3  7]
 [11 15]]


### Elementwise matrix operations - Multiplication

In [32]:
a = np.array([[1,3], [5,7]])
b = np.array([[2,4], [6,8]])
print(a)
print(b)
print(a * b)

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]

[[ 2 12]
 [30 56]]


### Matrix Product

In [35]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)
print(b.shape)

c = np.matmul(a, b)
print(c)
print(c.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 70  80  90]
 [158 184 210]]
(2, 3)


In [36]:
np.matmul(b, a)
# displays the following error:
# ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [37]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(np.dot(a,a))
print(a.dot(a))
print(np.matmul(a,a))

[[1 2]
 [3 4]]
(2, 2)
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


### Matrix transpose

In [38]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
print(m.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [39]:
m_t = m.T
m_t[3][1] = 200
print(m_t)
print(m)

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]
[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]
